# This file was generated by GoReleaser. DO NOT EDIT.
cask "simbeamd" do
  version "0.16.0"

  on_macos do
    on_intel do
      sha256 "4b05ad62a46812d734a7ceb561bfb6435a1b93ffd8ac1631abd2778e0987407f"
      url "https://github.com/kei-sidorov/simbeam/releases/download/v#{version}/simbeamd_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "3f38d391a6ae66fd36a4fbe57db78289a557f4d6e6d3957e3707113baae4f215"
      url "https://github.com/kei-sidorov/simbeam/releases/download/v#{version}/simbeamd_#{version}_darwin_arm64.tar.gz"
    end
  end

  name "simbeamd"
  desc "simbeam daemon — stream an iOS simulator from Mac to iPad"
  homepage "https://github.com/kei-sidorov/simbeam"

  livecheck do
    skip "Auto-generated on release."
  end
  depends_on formula: [
      "kei-sidorov/simbeam/simbeam-control",
    ]

  binary "simbeamd"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/simbeamd"]
    end
  end

  # No zap stanza required

  caveats <<~EOS
    simbeamd is shipped as an unsigned binary. The cask's post-install hook
    strips the macOS quarantine attribute so Gatekeeper should not block it.
    simbeamd drives simulators through simbeam-control (needs a full Xcode);
    idb_companion and ffmpeg are no longer required.
  EOS
end
