# This file was generated by GoReleaser. DO NOT EDIT.
cask "simbeamd" do
  version "0.21.0"

  on_macos do
    on_intel do
      sha256 "4e80ffa493b4bcabb080bcdb81c198b8801f89236f4c7bf7fb07fb2cc0c8a11c"
      url "https://github.com/kei-sidorov/simbeam/releases/download/v#{version}/simbeamd_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "12201df5f3ac4281ff71ce3b09468ffbb9a0f142def9f9714be51c0357e5b25c"
      url "https://github.com/kei-sidorov/simbeam/releases/download/v#{version}/simbeamd_#{version}_darwin_arm64.tar.gz"
    end
  end

  name "simbeamd"
  desc "simbeam daemon — stream an iOS simulator from Mac to iPad"
  homepage "https://github.com/kei-sidorov/simbeam"

  livecheck do
    skip "Auto-generated on release."
  end
  depends_on formula: [
      "kei-sidorov/simbeam/simbeam-control",
    ]

  binary "simbeamd"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/simbeamd"]
    end
  end

  # No zap stanza required

  caveats <<~EOS
    simbeamd is shipped as an unsigned binary. The cask's post-install hook
    strips the macOS quarantine attribute so Gatekeeper should not block it.
    simbeamd drives simulators through simbeam-control (needs a full Xcode);
    idb_companion and ffmpeg are no longer required.
  EOS
end
