# This file was generated by GoReleaser. DO NOT EDIT.
cask "simbeamd" do
  version "0.23.0"

  on_macos do
    on_intel do
      sha256 "d3e9f8a4e78d852ab3145b3db193dad30031765159943db54f6403a3d536ba22"
      url "https://github.com/kei-sidorov/simbeam/releases/download/v#{version}/simbeamd_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "798ac670de49432316cb359c8f1f6f901a9133ad820539aec81c63d0c62c1c1d"
      url "https://github.com/kei-sidorov/simbeam/releases/download/v#{version}/simbeamd_#{version}_darwin_arm64.tar.gz"
    end
  end

  name "simbeamd"
  desc "simbeam daemon — stream an iOS simulator from Mac to iPad"
  homepage "https://github.com/kei-sidorov/simbeam"

  livecheck do
    skip "Auto-generated on release."
  end
  depends_on formula: [
      "kei-sidorov/simbeam/simbeam-control",
    ]

  binary "simbeamd"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/simbeamd"]
    end
  end

  # No zap stanza required

  caveats <<~EOS
    simbeamd is shipped as an unsigned binary. The cask's post-install hook
    strips the macOS quarantine attribute so Gatekeeper should not block it.
    simbeamd drives simulators through simbeam-control (needs a full Xcode);
    idb_companion and ffmpeg are no longer required.
  EOS
end
